apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: catalogo
  region: us-east-2

iam:
  withOIDC: true

managedNodeGroups:
  - name: spot
    instanceTypes: ["t2.small"]
    spot: true
    minSize: 2
    maxSize: 4
    desiredCapacity: 2
    volumeSize: 20
    #ssh:
      #allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
      #publicKeyPath: ~/.ssh/id_rsa.pub
      #sourceSecurityGroupIds: ["sg-00241fbb12c607007"]
addons:
- name: vpc-cni
  #version: 1.7.5 # optional
  #attachPolicyARNs: #optional
  #- arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
    #serviceAccountRoleARN: arn:aws:iam::aws:policy/AmazonEKSCNIAccess # optional
  tags: # optional
    team: eks
  attachPolicy: # optional
    Statement:
    - Effect: Allow
      Action:
      - ec2:AssignPrivateIpAddresses
      - ec2:AttachNetworkInterface
      - ec2:CreateNetworkInterface
      - ec2:DeleteNetworkInterface
      - ec2:DescribeInstances
      - ec2:DescribeTags
      - ec2:DescribeNetworkInterfaces
      - ec2:DescribeInstanceTypes
      - ec2:DetachNetworkInterface
      - ec2:ModifyNetworkInterfaceAttribute
      - ec2:UnassignPrivateIpAddresses
      Resource: '*'

- name: coredns
- name: kube-proxy

