apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: apptest
  labels:
    app: worker
spec:
  replicas: 10
  selector:
    matchLabels:
      app: worker 
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: dockercoins/worker:v0.1
