apiVersion: v1
kind: Service
metadata:
  name: webui
  namespace: apptest
  labels:
    app: webui
spec:
  type: ClusterIP
  selector:
    app: webui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 
