apiVersion: v1
kind: Service
metadata:
  name: hasher
  namespace: apptest
  labels:
    app: hasher
spec:
  type: ClusterIP
  selector:
    app: hasher 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80  
