apiVersion: v1
kind: Service
metadata:
  name: httpenv-service
  namespace: httpenv
  labels:
    app: httpenv
spec:
  type: ClusterIP
  #type: NodePort
  selector:
    app: httpenv 
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888  
