apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"hasher"},"name":"hasher","namespace":"apptest"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"hasher"}},"template":{"metadata":{"labels":{"app":"hasher"}},"spec":{"containers":[{"image":"dockercoins/hasher:v0.1","name":"hasher"}]}}}}
  creationTimestamp: "2022-02-16T16:39:38Z"
  generation: 1
  labels:
    app: hasher
  name: hasher
  namespace: apptest
  resourceVersion: "54829"
  uid: fcec75e0-a3d5-4391-ad20-96ef4dda372d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hasher
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hasher
    spec:
      containers:
      - image: dockercoins/hasher:v0.1
        imagePullPolicy: IfNotPresent
        name: hasher
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-02-16T16:39:39Z"
    lastUpdateTime: "2022-02-16T16:39:39Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-02-16T16:39:38Z"
    lastUpdateTime: "2022-02-16T16:39:39Z"
    message: ReplicaSet "hasher-f98567769" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
