apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"hasher"},"name":"hasher","namespace":"apptest"},"spec":{"ports":[{"port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"hasher"},"type":"ClusterIP"}}
  creationTimestamp: "2022-02-24T16:25:27Z"
  labels:
    app: hasher
  name: hasher
  namespace: apptest
  resourceVersion: "575512"
  uid: 459d3136-741b-4f4a-853e-059844f0358d
spec:
  clusterIP: 10.110.157.11
  clusterIPs:
  - 10.110.157.11
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: hasher
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
