apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"redis"},"name":"redis","namespace":"apptest"},"spec":{"ports":[{"port":6379,"protocol":"TCP","targetPort":6379}],"selector":{"app":"redis"},"type":"ClusterIP"}}
  creationTimestamp: "2022-02-24T16:25:22Z"
  labels:
    app: redis
  name: redis
  namespace: apptest
  resourceVersion: "575504"
  uid: bdcb2f82-6471-4490-a43d-6b1e51dd75ea
spec:
  clusterIP: 10.104.68.210
  clusterIPs:
  - 10.104.68.210
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
