apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"rng"},"name":"rng","namespace":"apptest"},"spec":{"ports":[{"port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"rng"},"type":"ClusterIP"}}
  creationTimestamp: "2022-02-24T16:25:33Z"
  labels:
    app: rng
  name: rng
  namespace: apptest
  resourceVersion: "575521"
  uid: b430c81e-8910-4cd5-b461-7ea3ca360c3a
spec:
  clusterIP: 10.100.219.78
  clusterIPs:
  - 10.100.219.78
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: rng
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
