apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"webui"},"name":"webui","namespace":"apptest"},"spec":{"ports":[{"port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"webui"},"type":"ClusterIP"}}
  creationTimestamp: "2022-02-24T16:25:37Z"
  labels:
    app: webui
  name: webui
  namespace: apptest
  resourceVersion: "575528"
  uid: 01f701ff-2130-48ba-b4d5-116056590f68
spec:
  clusterIP: 10.98.30.12
  clusterIPs:
  - 10.98.30.12
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: webui
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
