apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"worker"},"name":"worker","namespace":"apptest"},"spec":{"replicas":10,"selector":{"matchLabels":{"app":"worker"}},"template":{"metadata":{"labels":{"app":"worker"}},"spec":{"containers":[{"image":"dockercoins/worker:v0.1","name":"worker"}]}}}}
  creationTimestamp: "2022-02-16T16:50:13Z"
  generation: 1
  labels:
    app: worker
  name: worker
  namespace: apptest
  resourceVersion: "56119"
  uid: 5d2a0434-51c8-47bc-9db5-849582e040af
spec:
  progressDeadlineSeconds: 600
  replicas: 10
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: worker
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: worker
    spec:
      containers:
      - image: dockercoins/worker:v0.1
        imagePullPolicy: IfNotPresent
        name: worker
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 10
  conditions:
  - lastTransitionTime: "2022-02-16T16:50:21Z"
    lastUpdateTime: "2022-02-16T16:50:21Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-02-16T16:50:13Z"
    lastUpdateTime: "2022-02-16T16:50:21Z"
    message: ReplicaSet "worker-554c657f4b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 10
  replicas: 10
  updatedReplicas: 10
